#!/bin/bash

GIT_CONNECTION=$(env -C $CODESPACE_VSCODE_FOLDER git remote -v | tail -1 | awk '{print $2}')
CURRENT_TOKEN=$(echo $GIT_CONNECTION | sed 's/https:.*:\(.*\)@gitlab.sofa.dev.*/\1/')
CURRENT_USER=$(echo $GIT_CONNECTION | sed 's/https:\/\/\(.*\):.*/\1/')
CURRENT_REPO=$(echo $GIT_CONNECTION | sed 's/.*@\(.*\)/\1/')

if [ $CURRENT_TOKEN != $GITLAB_TOKEN ]
then
    echo -n "New GitLab token detected. Updating the git repository connection..."
    NEW_CONNECTION="https://$CURRENT_USER:$GITLAB_TOKEN@$CURRENT_REPO"
    env -C $CODESPACE_VSCODE_FOLDER git remote set-url origin $NEW_CONNECTION
    if [ $? -eq 0 ]; then
        echo "OK"
    else
        echo "ERROR"
    fi
fi